# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindlg.ui'
#
# Created: Thu Oct  2 15:38:27 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainDlg(object):
    def setupUi(self, MainDlg):
        MainDlg.setObjectName("MainDlg")
        MainDlg.resize(785,512)
        MainDlg.setMinimumSize(QtCore.QSize(500,0))
        self.gridLayout = QtGui.QGridLayout(MainDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(MainDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.combo = QtGui.QComboBox(MainDlg)
        self.combo.setObjectName("combo")
        self.horizontalLayout.addWidget(self.combo)
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout,0,0,1,2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(MainDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.interval_spinbox = QtGui.QSpinBox(MainDlg)
        self.interval_spinbox.setMinimum(1)
        self.interval_spinbox.setMaximum(5000)
        self.interval_spinbox.setProperty("value",QtCore.QVariant(1000))
        self.interval_spinbox.setObjectName("interval_spinbox")
        self.horizontalLayout_2.addWidget(self.interval_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_2,0,2,1,1)
        spacerItem1 = QtGui.QSpacerItem(72,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1,1,0,1,2)
        self.status = QtGui.QLabel(MainDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status,1,2,1,1)
        self.text = QtGui.QLabel(MainDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(72)
        self.text.setFont(font)
        self.text.setTextFormat(QtCore.Qt.RichText)
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.gridLayout.addWidget(self.text,3,0,1,3)
        self.aufdecken = QtGui.QPushButton(MainDlg)
        self.aufdecken.setObjectName("aufdecken")
        self.gridLayout.addWidget(self.aufdecken,5,0,1,1)
        spacerItem2 = QtGui.QSpacerItem(553,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2,5,1,1,1)
        self.button = QtGui.QPushButton(MainDlg)
        self.button.setObjectName("button")
        self.gridLayout.addWidget(self.button,5,2,1,1)
        spacerItem3 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3,4,0,1,1)
        spacerItem4 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4,2,0,1,1)

        self.retranslateUi(MainDlg)
        QtCore.QMetaObject.connectSlotsByName(MainDlg)

    def retranslateUi(self, MainDlg):
        MainDlg.setWindowTitle(QtGui.QApplication.translate("MainDlg", "Gedächtnistest   ---  (c) Carsten Niehaus 2008", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainDlg", "Liste:", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Einsilbig 1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Einsilbig 2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Mehrsilbig 1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Mehrsilbig 2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Zweisilbig", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Ähnlicher Klang 1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Ähnlicher Klang 2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Ähnlicher Klang 3", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Ähnlicher Klang 4", None, QtGui.QApplication.UnicodeUTF8))
        self.combo.addItem(QtGui.QApplication.translate("MainDlg", "Ähnlicher Klang 5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainDlg", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.interval_spinbox.setWhatsThis(QtGui.QApplication.translate("MainDlg", "Die Anzahl an Millisekunden zwischen zwei Begriffen", None, QtGui.QApplication.UnicodeUTF8))
        self.interval_spinbox.setSuffix(QtGui.QApplication.translate("MainDlg", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.text.setText(QtGui.QApplication.translate("MainDlg", "\"Start\" drücken", None, QtGui.QApplication.UnicodeUTF8))
        self.aufdecken.setText(QtGui.QApplication.translate("MainDlg", "&Aufdecken", None, QtGui.QApplication.UnicodeUTF8))
        self.button.setText(QtGui.QApplication.translate("MainDlg", "&Start", None, QtGui.QApplication.UnicodeUTF8))

