# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindlg.ui'
#
# Created: Wed Mar 18 15:58:27 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainDlg(object):
    def setupUi(self, MainDlg):
        MainDlg.setObjectName("MainDlg")
        MainDlg.resize(537, 495)
        self.gridLayout = QtGui.QGridLayout(MainDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(MainDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.klassenCombo = QtGui.QComboBox(MainDlg)
        self.klassenCombo.setObjectName("klassenCombo")
        self.gridLayout.addWidget(self.klassenCombo, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(270, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.checkBox = QtGui.QCheckBox(MainDlg)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(MainDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.name_le = QtGui.QLineEdit(MainDlg)
        self.name_le.setObjectName("name_le")
        self.horizontalLayout_2.addWidget(self.name_le)
        self.such_knopf = QtGui.QPushButton(MainDlg)
        self.such_knopf.setObjectName("such_knopf")
        self.horizontalLayout_2.addWidget(self.such_knopf)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 4)
        self.tabelle = QtGui.QTableWidget(MainDlg)
        self.tabelle.setObjectName("tabelle")
        self.tabelle.setColumnCount(5)
        self.tabelle.setRowCount(28)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setVerticalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabelle.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tabelle, 2, 0, 1, 4)
        self.closeButton = QtGui.QPushButton(MainDlg)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 3, 0, 1, 4)

        self.retranslateUi(MainDlg)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), MainDlg.accept)
        QtCore.QMetaObject.connectSlotsByName(MainDlg)

    def retranslateUi(self, MainDlg):
        MainDlg.setWindowTitle(QtGui.QApplication.translate("MainDlg", "Passwort-Finder (KGS Rastede)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainDlg", "Klasse:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainDlg", "alle Schüler anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainDlg", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.such_knopf.setText(QtGui.QApplication.translate("MainDlg", "&Suchen", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(8).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(9).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(10).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(11).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(12).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(13).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(14).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(15).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(16).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(17).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(18).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(19).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(20).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(21).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(22).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(23).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(24).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(25).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(26).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.verticalHeaderItem(27).setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainDlg", "Klasse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainDlg", "Vorname", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainDlg", "Nachname", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainDlg", "Nutzername", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainDlg", "Passwort", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("MainDlg", "Close", None, QtGui.QApplication.UnicodeUTF8))

