# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindlg.ui'
#
# Created: Thu Sep 18 16:48:23 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainDlg(object):
    def setupUi(self, MainDlg):
        MainDlg.setObjectName("MainDlg")
        MainDlg.resize(537,495)
        self.gridLayout = QtGui.QGridLayout(MainDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(MainDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.klassenCombo = QtGui.QComboBox(MainDlg)
        self.klassenCombo.setObjectName("klassenCombo")
        self.horizontalLayout.addWidget(self.klassenCombo)
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout,0,0,1,1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(MainDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.name_le = QtGui.QLineEdit(MainDlg)
        self.name_le.setObjectName("name_le")
        self.horizontalLayout_2.addWidget(self.name_le)
        self.such_knopf = QtGui.QPushButton(MainDlg)
        self.such_knopf.setObjectName("such_knopf")
        self.horizontalLayout_2.addWidget(self.such_knopf)
        self.gridLayout.addLayout(self.horizontalLayout_2,1,0,1,1)
        self.tabelle = QtGui.QTableWidget(MainDlg)
        self.tabelle.setObjectName("tabelle")
        self.gridLayout.addWidget(self.tabelle,2,0,1,1)
        self.closeButton = QtGui.QPushButton(MainDlg)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton,3,0,1,1)

        self.retranslateUi(MainDlg)
        QtCore.QObject.connect(self.closeButton,QtCore.SIGNAL("clicked()"),MainDlg.accept)
        QtCore.QMetaObject.connectSlotsByName(MainDlg)

    def retranslateUi(self, MainDlg):
        MainDlg.setWindowTitle(QtGui.QApplication.translate("MainDlg", "Passwort-Finder (KGS Rastede)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainDlg", "Klasse:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainDlg", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.such_knopf.setText(QtGui.QApplication.translate("MainDlg", "&Suchen", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.clear()
        self.tabelle.setColumnCount(5)
        self.tabelle.setRowCount(28)
        headerItem = QtGui.QTableWidgetItem()
        headerItem.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(0,headerItem)
        headerItem1 = QtGui.QTableWidgetItem()
        headerItem1.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(1,headerItem1)
        headerItem2 = QtGui.QTableWidgetItem()
        headerItem2.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(2,headerItem2)
        headerItem3 = QtGui.QTableWidgetItem()
        headerItem3.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(3,headerItem3)
        headerItem4 = QtGui.QTableWidgetItem()
        headerItem4.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(4,headerItem4)
        headerItem5 = QtGui.QTableWidgetItem()
        headerItem5.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(5,headerItem5)
        headerItem6 = QtGui.QTableWidgetItem()
        headerItem6.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(6,headerItem6)
        headerItem7 = QtGui.QTableWidgetItem()
        headerItem7.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(7,headerItem7)
        headerItem8 = QtGui.QTableWidgetItem()
        headerItem8.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(8,headerItem8)
        headerItem9 = QtGui.QTableWidgetItem()
        headerItem9.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(9,headerItem9)
        headerItem10 = QtGui.QTableWidgetItem()
        headerItem10.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(10,headerItem10)
        headerItem11 = QtGui.QTableWidgetItem()
        headerItem11.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(11,headerItem11)
        headerItem12 = QtGui.QTableWidgetItem()
        headerItem12.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(12,headerItem12)
        headerItem13 = QtGui.QTableWidgetItem()
        headerItem13.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(13,headerItem13)
        headerItem14 = QtGui.QTableWidgetItem()
        headerItem14.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(14,headerItem14)
        headerItem15 = QtGui.QTableWidgetItem()
        headerItem15.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(15,headerItem15)
        headerItem16 = QtGui.QTableWidgetItem()
        headerItem16.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(16,headerItem16)
        headerItem17 = QtGui.QTableWidgetItem()
        headerItem17.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(17,headerItem17)
        headerItem18 = QtGui.QTableWidgetItem()
        headerItem18.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(18,headerItem18)
        headerItem19 = QtGui.QTableWidgetItem()
        headerItem19.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(19,headerItem19)
        headerItem20 = QtGui.QTableWidgetItem()
        headerItem20.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(20,headerItem20)
        headerItem21 = QtGui.QTableWidgetItem()
        headerItem21.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(21,headerItem21)
        headerItem22 = QtGui.QTableWidgetItem()
        headerItem22.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(22,headerItem22)
        headerItem23 = QtGui.QTableWidgetItem()
        headerItem23.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(23,headerItem23)
        headerItem24 = QtGui.QTableWidgetItem()
        headerItem24.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(24,headerItem24)
        headerItem25 = QtGui.QTableWidgetItem()
        headerItem25.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(25,headerItem25)
        headerItem26 = QtGui.QTableWidgetItem()
        headerItem26.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(26,headerItem26)
        headerItem27 = QtGui.QTableWidgetItem()
        headerItem27.setText(QtGui.QApplication.translate("MainDlg", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setVerticalHeaderItem(27,headerItem27)
        headerItem28 = QtGui.QTableWidgetItem()
        headerItem28.setText(QtGui.QApplication.translate("MainDlg", "Klasse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setHorizontalHeaderItem(0,headerItem28)
        headerItem29 = QtGui.QTableWidgetItem()
        headerItem29.setText(QtGui.QApplication.translate("MainDlg", "Vorname", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setHorizontalHeaderItem(1,headerItem29)
        headerItem30 = QtGui.QTableWidgetItem()
        headerItem30.setText(QtGui.QApplication.translate("MainDlg", "Nachname", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setHorizontalHeaderItem(2,headerItem30)
        headerItem31 = QtGui.QTableWidgetItem()
        headerItem31.setText(QtGui.QApplication.translate("MainDlg", "Nutzername", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setHorizontalHeaderItem(3,headerItem31)
        headerItem32 = QtGui.QTableWidgetItem()
        headerItem32.setText(QtGui.QApplication.translate("MainDlg", "Passwort", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelle.setHorizontalHeaderItem(4,headerItem32)
        self.closeButton.setText(QtGui.QApplication.translate("MainDlg", "Close", None, QtGui.QApplication.UnicodeUTF8))

